name: Deploy to Staging

on:
  push:
    branches: [staging]

jobs:
  deploy:
    uses: ./.github/workflows/deploy-eb-reusable.yaml
    with:
      environment: staging
      eb_env_name: employee-app-staging
      eb_app_name: employee-app-staging
      s3_key_prefix: employee-app/staging
