name: Deploy to Production

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  deploy:
    uses: ./.github/workflows/deploy-eb-reusable.yaml
    with:
      environment: production
      eb_env_name: employee-app-production
      eb_app_name: employee-app-production
      s3_key_prefix: employee-app/prod
    secrets: inherit