name: Deploy to Dev

on:
  push:
    branches: [develop]

jobs:
  deploy:
    uses: ./.github/workflows/deploy-eb-reusable.yaml
    with:
      environment: develop
      eb_env_name: employee-app-dev
      eb_app_name: employee-app
      s3_key_prefix: employee-app/dev
    secrets: inherit
